### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2192' in position 17: ordinal not in range(256)

### ISSUE THREAD

**Issue by teto** [Mic92/nixpkgs-review#157] opened 2020-12-15 11:48 UTC
I recently got this error:
```
nixpkgs-review pr 106928                                                                                                                                                         
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/106928/head:refs/nixpkgs-review/1
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 40 (delta 19), reused 17 (delta 14), pack-reused 7
Unpacking objects: 100% (40/40), 233.75 KiB | 195.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
   12f367b51ca..0cb7962a12b  master                -> refs/nixpkgs-review/0
 + 9ba98aa7dbb...38eba5c8d3c refs/pull/106928/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/teto/.cache/nixpkgs-review/pr-106928-1/nixpkgs 0cb7962a12b68f094d25aeb1fc24bc0f32ceeb7c
Preparing worktree (detached HEAD 0cb7962a12b)
Updating files: 100% (23520/23520), done.
HEAD is now at 0cb7962a12b Merge pull request #106899 from ttuegel/nixos-plasma-test-kded
$ nix-env -f /home/teto/.cache/nixpkgs-review/pr-106928-1/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 38eba5c8d3c939c1753bb28c284a7c619fb4d2b6
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/teto/.cache/nixpkgs-review/pr-106928-1/nixpkgs -qaP --xml --out-path --show-trace --meta
1 package updated:
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/qfwzg73glcjrdlhsfkdj1449711ia5yz-nixpkgs-review-2.5.0/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/qfwzg73glcjrdlhsfkdj1449711ia5yz-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/qfwzg73glcjrdlhsfkdj1449711ia5yz-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/cli/__init__.py", line 228, in main
    args.func(args)
  File "/nix/store/qfwzg73glcjrdlhsfkdj1449711ia5yz-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/cli/pr.py", line 60, in pr_command
    contexts.append((pr, review.build_pr(pr)))
  File "/nix/store/qfwzg73glcjrdlhsfkdj1449711ia5yz-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 201, in build_pr
    return self.build_commit(base_rev, pr_rev)
  File "/nix/store/qfwzg73glcjrdlhsfkdj1449711ia5yz-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 159, in build_commit
    print_updates(changed_pkgs, removed_pkgs)
  File "/nix/store/qfwzg73glcjrdlhsfkdj1449711ia5yz-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 92, in print_updates
    print_packages(updated, "updated")
  File "/nix/store/qfwzg73glcjrdlhsfkdj1449711ia5yz-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 59, in print_packages
    print(" ".join(names))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2192' in position 17: ordinal not in range(256)
nixpkgs-review pr 106928  99.98s user 6.10s system 114% cpu 1:32.66 total
```
as a datapoint, I had a similar error with `alot` recently so maybe it's my system or an update of nixos-unstable.
Nixpkgs-review worked fine on other PRs

**Comment by Mic92** [comment] 2020-12-15 14:02
Do you have non-unicode locales?

**Comment by Mic92** [comment] 2021-02-21 10:17
closing because issuer no longer respond and it cannot be reproduced otherwise.

**Closed by Mic92** 2021-02-21 10:17 UTC

**Comment by teto** [comment] 2021-02-21 10:57
Yes that was a non-unicode locale sry for not responding.
