### ISSUE TITLE
An error being thrown now halts a review

### ISSUE THREAD

**Issue by jonringer** [Mic92/nixpkgs-review#82] opened 2020-02-13 08:12 UTC
An error being thrown, including when it gets thrown with python's `disabled` usage now causes an review to be halted altogether:

```
$ nix-review pr 79351
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/79351/head:refs/nixpkgs-review/1
$ git worktree add /home/jon/.cache/nixpkgs-review/pr-79351-5/nixpkgs 3b7f5c6762bb174bd9951a697b636e1db531e98a
Preparing worktree (detached HEAD 3b7f5c6762b)
HEAD is now at 3b7f5c6762b python3Packages.snowflake-connector-python: 2.1.2 -> 2.2.0
$ git merge --no-commit c37276edf0f11d74c117b3a491251749137277ba
Auto-merging pkgs/development/tools/aws-sam-cli/default.nix
Automatic merge went well; stopped before committing as requested
error: seaborn-0.10.0 not supported for interpreter python2.7
(use '--show-trace' to show detailed location information)
nix eval --json (import /nix/store/9yy1gv7az9mqxak6jsqkyppb4g1zvzl0-nixpkgs-review-2.1.1/lib/python3.7/site-packages/nixpkgs_review/nix/evalAttrs.nix /tmp/tmp4485moms) failed to run, /tmp/tmp4485moms was stored inspection
https://github.com/NixOS/nixpkgs/pull/79351 failed to build
```

nixpkgs-review==2.1.1

**Comment by jonringer** [comment] 2020-02-13 08:22
Did some more research, apparently this occurs when master has an affected package disabled (by either meta.broken or disabled). However, rebasing the brnach on top of the target branch avoids this.

**Comment by Mic92** [comment] 2020-02-13 11:01
Would this work as a work-around in the meantime? `nixpkgs-review pr --checkout commit 79351`

**Comment by Mic92** [comment] 2020-02-13 11:04
I cannot reproduce it at the moment. Can you provide me the temporary directory in case eval fails?

**Comment by jonringer** [comment] 2020-02-13 16:49
If I find another which shows this behaviour, I'll update this thread. The original PR rebased their commit and it's no longer an issue

**Comment by jonringer** [comment] 2020-02-17 00:34
I haven't found another example. closing for now

**Comment by jonringer** [comment] 2020-02-18 00:04
found another PR https://github.com/NixOS/nixpkgs/pull/77714

**Comment by jonringer** [comment] 2020-02-18 00:04
```
$ git merge --no-commit 72f9a986542209f5b0d33289e5e40dd8fe3d9204
Automatic merge went well; stopped before committing as requested
error: Mezzanine-4.3.1 not supported for interpreter python3.7
(use '--show-trace' to show detailed location information)
```

**Comment by Mic92** [comment] 2020-02-18 09:56
Using `nix-review pr --eval local 77714` is the current workaround. ofborgs evaluation result is stalled in that case.

**Comment by Mic92** [comment] 2020-02-18 10:26
I don't know how to fix this bug. 
pythonPackages already aborts the evaluation when attempting to retrieve the derivation value: https://github.com/Mic92/nixpkgs-review/blob/master/nixpkgs_review/nix/evalAttrs.nix#L15
However I need it to differentiate between a package that does not exists and a package that is marked as broken.

**Comment by Mic92** [comment] 2020-02-18 10:27
cc @Fridh

**Comment by Mic92** [comment] 2020-02-18 10:46
I found a workaround.

**Closed** 2020-02-18 10:48 UTC

**Comment by jonringer** [comment] 2020-02-18 16:57
very nice :)
