### ISSUE TITLE
`passthru.tests` should be run automatically

### ISSUE THREAD

**Issue by erikarvstedt** [Mic92/nixpkgs-review#297] opened 2022-12-29 09:31 UTC
Package update PR https://github.com/NixOS/nixpkgs/pull/206835 broke the corresponding module (later [fixed here](https://github.com/NixOS/nixpkgs/pull/207754)).

This could have been prevented if the standard review command (`nixpkgs-review pr 206835`) would automatically run the package-specific NixOS tests defined in `passthru.tests`. 

Instead, reviewers need to manually run the test with an extra command:
```bash
nixpkgs-review pr 206835
nixpkgs-review pr -p nixosTests.paperless 206835
```
This is error-prone, not least because the NixOS test name can differ from the package name (like in this case).

cc @NobbZ, @SuperSandro2000

**Comment by NobbZ** [comment] 2022-12-29 09:57
There should be a way to opt out from running the tests then, as they might involve virtualisation, which might not be available for everyone.

Any generated output, and perhaps the PR template should be adjusted then to also tell whether tests or not have been (successfully) ran.

**Comment by Mic92** [comment] 2022-12-29 10:19
Duplicate of https://github.com/Mic92/nixpkgs-review/issues/77

**Closed** 2022-12-30 01:57 UTC
